version: '3.8'

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: digger_app
    entrypoint: "go run web-digger"
    restart: always
    tty: true
    ports:
      - 8000:8000
    networks:
      - default
    volumes:
      - .:/go/web-digger

networks:
  default:
